"""0.0.7

Revision ID: 004ec3ee751c
Revises: 62abafcfc3ff
Create Date: 2023-05-19 16:46:56.832726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004ec3ee751c'
down_revision = '62abafcfc3ff'
branch_labels = None
depends_on = None


def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('CHECKING', 'SAVINGS', 'CREDIT_CARD', 'LOAN', 'INVESTMENT', name='accounttype'), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_id'), 'bank_accounts', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('colorCode', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('merchants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_id'), 'merchants', ['id'], unique=False)


    #op.add_column('budgets', sa.Column('category_id', sa.Integer(), nullable=False))
    #op.create_foreign_key(None, 'budgets', 'categories', ['category_id'], ['id'])
    with op.batch_alter_table("budgets") as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer,
                            sa.ForeignKey('categories.id', name='fk_budgets_categories')))

    op.drop_column('budgets', 'category')

    #op.add_column('transactions', sa.Column('merchant_id', sa.Integer(), nullable=True))
    #op.create_foreign_key(None, 'transactions', 'merchants', ['merchant_id'], ['id'])
    with op.batch_alter_table("transactions") as batch_op:
        batch_op.add_column(sa.Column('merchant_id', sa.Integer,
                            sa.ForeignKey('merchants.id', name='fk_transactions_merchants')))


    #op.add_column('transactions', sa.Column('bank_account_id', sa.Integer(), nullable=True))
    #op.create_foreign_key(None, 'transactions', 'bank_accounts', ['bank_account_id'], ['id'])
    with op.batch_alter_table("transactions") as batch_op:
        batch_op.add_column(sa.Column('bank_account_id', sa.Integer,
                            sa.ForeignKey('bank_accounts.id', name='fk_transactions_bank_accounts')))




    op.drop_column('transactions', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'bank_account_id')
    op.drop_column('transactions', 'merchant_id')
    op.add_column('budgets', sa.Column('category', sa.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.drop_column('budgets', 'category_id')
    op.drop_index(op.f('ix_merchants_id'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_bank_accounts_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
