"""0.0.5

Revision ID: 4236000a2389
Revises: 6139f991bf5d
Create Date: 2023-05-14 11:22:36.348854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4236000a2389'
down_revision = '6139f991bf5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('import_batches') as batch_op:
    #     batch_op.alter_column('user_id',
    #                           existing_type=sa.INTEGER(),
    #                           nullable=False)
    #     batch_op.drop_constraint(constraint_name=None, type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'import_batches', 'users', ['user_id'], ['id'])
    # op.alter_column('import_batches', 'user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # ### end Alembic commands ###
