"""0.0.3

Revision ID: 79dfb32e683b
Revises: 8f686b101427
Create Date: 2023-05-14 10:02:44.173238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79dfb32e683b'
down_revision = '8f686b101427'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_accounts',
    sa.Column('database', sa.String(), nullable=True),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_accounts_id'), 'user_accounts', ['id'], unique=False)
    op.add_column('budgets', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('import_batches', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    #op.add_column('users', sa.Column('user_account_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    #op.create_foreign_key(None, 'users', 'user_accounts', ['user_account_id'], ['id'])

    op.drop_column('users', 'database')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('database', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'user_account_id')
    op.drop_column('transactions', 'is_deleted')
    op.drop_column('import_batches', 'is_deleted')
    op.drop_column('budgets', 'is_deleted')
    op.drop_index(op.f('ix_user_accounts_id'), table_name='user_accounts')
    op.drop_table('user_accounts')
    # ### end Alembic commands ###
